appCloudfrontdEnv:
  component: "@sls-next/serverless-component@1.17.0"
  inputs:
    domain:
      - ${env.subdomain}
      - ${env.domain}
    cloudfront:
      defaults:
        forward:
          headers:
            [
              CloudFront-Is-Desktop-Viewer,
              CloudFront-Is-Mobile-Viewer,
              CloudFront-Is-Tablet-Viewer,
              Host
            ]
